on: 
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main
      - '**'
  schedule:
    - cron: "5 8 * * 0"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build for linux/amd64
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/base:latest, ${{ secrets.DOCKERHUB_USERNAME }}/base:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/base:amd64-buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/base:amd64-buildcache,mode=max

      - name: Push linux/amd64 build to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/base:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/base:${{ github.sha }}
  
